Starting task Fuzz...
Using python: 'python.exe' (Python 3.11.0)

ERROR: Results analyzer for logs in D:\Workspace\apiTesting\report\Restler\4\Fuzz failed.

Request coverage (successful / total): 0 / 14
Attempted requests: 0 / 14
No bugs were found.
Task Fuzz succeeded.
Collecting logs...